/**
 * Core type definitions for @vudo/runtime
 */

// ============================================================================
// Gene Layout Types
// ============================================================================

/** Supported primitive types in WASM memory */
export type GeneFieldType = 'i32' | 'i64' | 'f32' | 'f64' | 'bool' | 'string';

/** A single field in a Gene layout */
export interface GeneField {
  /** Field name matching DOL declaration */
  name: string;
  /** WASM type */
  type: GeneFieldType;
  /** Byte offset from struct start */
  offset: number;
}

/** Memory layout for a Gene (generated by dol-codegen) */
export interface GeneLayout {
  /** Gene name from DOL source */
  name: string;
  /** Field definitions with offsets */
  fields: GeneField[];
  /** Total size in bytes */
  size: number;
  /** Alignment requirement */
  alignment: number;
}

/** Type helper for gene values */
export type GeneValues<T extends GeneLayout> = {
  [K in T['fields'][number]['name']]: T['fields'][number] extends { name: K; type: infer Type }
    ? Type extends 'i64' ? bigint
    : Type extends 'f64' ? number
    : Type extends 'f32' ? number
    : Type extends 'i32' ? number
    : Type extends 'bool' ? boolean
    : Type extends 'string' ? string
    : unknown
    : unknown;
};

// ============================================================================
// Spirit Types
// ============================================================================

/** Options for loading a Spirit */
export interface LoadOptions {
  /** Custom host function implementations */
  imports?: Record<string, WebAssembly.ImportValue>;
  /** Memory configuration */
  memory?: {
    /** Initial memory pages (64KB each) */
    initial?: number;
    /** Maximum memory pages */
    maximum?: number;
  };
  /** Enable debug logging */
  debug?: boolean;
  /** Loa registry for service injection */
  loas?: LoaRegistry;
}

/** Spirit instance returned by loader */
export interface SpiritInstance {
  /** Call an exported function */
  call<R = unknown>(name: string, args?: unknown[]): R;
  /** Get typed interface */
  as<T extends object>(): T;
  /** Access memory manager */
  readonly memory: MemoryManager;
  /** Raw WASM exports */
  readonly exports: WebAssembly.Exports;
}

// ============================================================================
// Loa (Service) Types
// ============================================================================

/** A Loa (service) that can be injected into Spirits */
export interface Loa {
  /** Unique service name */
  name: string;
  /** Semantic version */
  version: string;
  /** List of capabilities provided */
  capabilities: string[];
  /** Factory function returning host function implementations */
  provides: (context: LoaContext) => Record<string, WebAssembly.ImportValue>;
}

/** Context passed to Loa providers */
export interface LoaContext {
  /** WASM memory for the Spirit */
  memory: WebAssembly.Memory;
  /** Allocator for memory operations */
  alloc: (size: number) => number;
  /** Debug mode flag */
  debug: boolean;
}

/** Registry for managing Loa services */
export interface LoaRegistry {
  /** Register a new Loa */
  register(loa: Loa): void;
  /** Get a Loa by name */
  get(name: string): Loa | undefined;
  /** Check if a Loa is registered */
  has(name: string): boolean;
  /** Get all registered Loas */
  all(): Loa[];
  /** Unregister a Loa */
  unregister(name: string): boolean;
  /** Build imports object from registered Loas */
  buildImports(context: LoaContext): Record<string, WebAssembly.ImportValue>;
}

// ============================================================================
// Séance (Session) Types
// ============================================================================

/** A Séance manages multiple Spirit instances */
export interface SeanceInstance {
  /** Summon a Spirit into the session */
  summon(name: string, source: string | ArrayBuffer): Promise<void>;
  /** Invoke a function on a summoned Spirit */
  invoke<R = unknown>(spiritName: string, funcName: string, args?: unknown[]): Promise<R>;
  /** Get a summoned Spirit by name */
  getSpirit(name: string): SpiritInstance | undefined;
  /** Dismiss the session and clean up */
  dismiss(): Promise<void>;
  /** List all summoned Spirit names */
  spirits(): string[];
}

// ============================================================================
// Memory Manager Types
// ============================================================================

/** Memory manager for a Spirit instance */
export interface MemoryManager {
  /** Allocate bytes, returns pointer */
  alloc(size: number, align?: number): number;
  /** Free allocated memory (no-op for bump allocator) */
  free(ptr: number): void;
  /** Reset allocator */
  reset(): void;
  /** Read a Gene from memory */
  readGene<T extends GeneLayout>(ptr: number, layout: T): Record<string, unknown>;
  /** Write a Gene to memory */
  writeGene<T extends GeneLayout>(ptr: number, values: Record<string, unknown>, layout: T): void;
  /** Encode a string, returns pointer */
  encodeString(str: string): number;
  /** Decode a string from pointer */
  decodeString(ptr: number): string;
  /** Get raw memory buffer */
  readonly buffer: ArrayBuffer;
  /** Get current allocation offset */
  readonly offset: number;
}
