// Generated by dol-codegen from Metal DOL declarations
// Do not edit manually - regenerate from source .dol files

// Source: dol/token.dol
#[derive(Debug, Clone)]
pub struct TokenKind {
    pub r#type: String,
}

impl TokenKind {
    pub fn new(r#type: String) -> Self {
        Self {
            r#type,
        }
    }
}


#[derive(Debug, Clone)]
pub struct Span {
    pub start: String,
    pub end: String,
    pub line: String,
    pub column: String,
}

impl Span {
    pub fn new(start: String, end: String, line: String, column: String) -> Self {
        Self {
            start,
            end,
            line,
            column,
        }
    }
}


#[derive(Debug, Clone)]
pub struct Token {
    pub kind: String,
    pub span: String,
    pub text: String,
}

impl Token {
    pub fn new(kind: String, span: String, text: String) -> Self {
        Self {
            kind,
            span,
            text,
        }
    }

    pub fn is_keyword() -> bool {
        match self.kind {
    Module => {
    return true;
},
    Use => {
    return true;
},
    Pub => {
    return true;
},
    Gene => {
    return true;
},
    Trait => {
    return true;
},
    System => {
    return true;
},
    Constraint => {
    return true;
},
    Evolves => {
    return true;
},
    Fun => {
    return true;
},
    Return => {
    return true;
},
    If => {
    return true;
},
    Else => {
    return true;
},
    Match => {
    return true;
},
    For => {
    return true;
},
    While => {
    return true;
},
    Loop => {
    return true;
},
    Break => {
    return true;
},
    Continue => {
    return true;
},
    Has => {
    return true;
},
    Is => {
    return true;
},
    Type => {
    return true;
},
    Law => {
    return true;
},
    Where => {
    return true;
},
    Sex => {
    return true;
},
    Var => {
    return true;
},
    _ => {
    return false;
}
};
    }

    pub fn is_operator() -> bool {
        match self.kind {
    Plus => {
    return true;
},
    Minus => {
    return true;
},
    Star => {
    return true;
},
    Slash => {
    return true;
},
    Percent => {
    return true;
},
    Pipe => {
    return true;
},
    Compose => {
    return true;
},
    Quote => {
    return true;
},
    Bang => {
    return true;
},
    Question => {
    return true;
},
    _ => {
    return false;
}
};
    }
}


pub fn keyword_lookup(text: String) -> Option<TokenKind> {
    match text {
    "module" => {
    return Some(TokenKind::Module);
},
    "use" => {
    return Some(TokenKind::Use);
},
    "pub" => {
    return Some(TokenKind::Pub);
},
    "gene" => {
    return Some(TokenKind::Gene);
},
    "trait" => {
    return Some(TokenKind::Trait);
},
    "system" => {
    return Some(TokenKind::System);
},
    "constraint" => {
    return Some(TokenKind::Constraint);
},
    "evolves" => {
    return Some(TokenKind::Evolves);
},
    "exegesis" => {
    return Some(TokenKind::Exegesis);
},
    "fun" => {
    return Some(TokenKind::Fun);
},
    "return" => {
    return Some(TokenKind::Return);
},
    "if" => {
    return Some(TokenKind::If);
},
    "else" => {
    return Some(TokenKind::Else);
},
    "match" => {
    return Some(TokenKind::Match);
},
    "for" => {
    return Some(TokenKind::For);
},
    "while" => {
    return Some(TokenKind::While);
},
    "loop" => {
    return Some(TokenKind::Loop);
},
    "in" => {
    return Some(TokenKind::In);
},
    "break" => {
    return Some(TokenKind::Break);
},
    "continue" => {
    return Some(TokenKind::Continue);
},
    "has" => {
    return Some(TokenKind::Has);
},
    "is" => {
    return Some(TokenKind::Is);
},
    "type" => {
    return Some(TokenKind::Type);
},
    "law" => {
    return Some(TokenKind::Law);
},
    "where" => {
    return Some(TokenKind::Where);
},
    "requires" => {
    return Some(TokenKind::Requires);
},
    "provides" => {
    return Some(TokenKind::Provides);
},
    "sex" => {
    return Some(TokenKind::Sex);
},
    "var" => {
    return Some(TokenKind::Var);
},
    "true" => {
    return Some(TokenKind::BoolTrue);
},
    "false" => {
    return Some(TokenKind::BoolFalse);
},
    _ => {
    return None;
}
};
}


